### ISSUE TITLE
Parity UI wallet doesn't scale to a large number of accounts, "There are currently no accounts or addresses to display"

### ISSUE THREAD

**Issue by lampshade9909** [parity-js/shell#127] opened 2018-05-30 18:39 UTC
> I'm running:
>
> - **Parity client version**: Parity v1.10.2-20180423 beta
> - **Parity UI version**: Version 0.1.1 (0.1.1)
> - **Operating system**: MacOS
> - **Installed via**: installer
> - **Fully synchronized**: yes
> - **Network**: ethereum
> - **I tried to restart both Parity UI and Parity Ethereum client**: yes

The Parity UI Wallet doesn't seem to function when I have a large number of accounts.   The web version used to function well even with ~80 accounts, but once I updated to Parity UI it seems to stop around ~20-30 (sometimes it'll work with ~25, other times it won't.  But it will never work with 80).  

This is what I see when I try to view a large number of accounts at once, "There are currently no accounts or addresses to display": 
<img width="578" alt="screen shot 2018-05-30 at 11 31 17 am" src="https://user-images.githubusercontent.com/5184617/40740487-d8576574-63fd-11e8-9585-b448cf56a974.png">

I would expect that the UI could handle a large number of accounts even if it takes a long time to load all of their balances.  Unfortunately, since switching to Parity UI I can't go over about 10.  Once I get to around ~25 it breaks and won't show me any accounts.  

I personally have about 80 accounts but cannot see all 80 at once.  To work around this, I'm forced to kill my node and kill Parity UI.  Temporarily move about 70 out of my 80 json key files to some other location, then leave only ~10 out of the 80 json key files to the location it's expecting.  Restart my node, restart Parity UI.  Then I can see exactly those 10.

**Comment by Tbaut** [comment] 2018-05-31 09:53
Could you open the dev console of Parity UI (ctrl-shift-i) and paste a screenshot of it when the problem happens so that we can see the errors?

**Comment by lampshade9909** [comment] 2018-05-31 18:35
That shortcut doesn't seem to do anything.  I'm on a mac, is it different on a mac? I've tried a bunch of possibilities but don't see a console.

**Comment by lampshade9909** [comment] 2018-05-31 18:48
`UI version 0.1.2
bundle.js:1 js-ui: i18n in `ContextProvider` disabled
get @ bundle.js:1
chrome-extension://REMOVEDFORPRIVACY/u2f-comms.html Failed to load resource: net::ERR_NOT_IMPLEMENTED
bundle.js:1 registryAddress REMOVEDFORPRIVACY
bundle.js:1 [checkUpgrade] available: null version: Object consensusCapability: unknown
bundle.js:1 starting Signer Provider...
bundle.js:1 started Signer Provider
bundle.js:1 starting Status Provider...
bundle.js:1 registry at REMOVEDFORPRIVACY, code REMOVEDFORPRIVACY, version 2
bundle.js:1 loadAccounts SyntaxError: Unexpected string in JSON at position 17
    at JSON.parse (<anonymous>)
    at bundle.js:1
    at Array.reduce (<anonymous>)
    at r (bundle.js:1)
    at <anonymous>
(anonymous) @ bundle.js:1
bundle.js:1 started Status Provider
bundle.js:1 starting Personal Provider...
bundle.js:1 [lookupAddress] signaturereg: REMOVEDFORPRIVACY
bundle.js:1 [lookupAddress] githubhint: REMOVEDFORPRIVACY
bundle.js:1 [lookupAddress] tokenreg: REMOVEDFORPRIVACY
bundle.js:1 [lookupAddress] dappreg: REMOVEDFORPRIVACY
bundle.js:1 [lookupAddress] badgereg: REMOVEDFORPRIVACY
bundle.js:1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('chrome-extension://REMOVEDFORPRIVACY') does not match the recipient window's origin ('null').
(anonymous) @ bundle.js:1
bundle.js:1 Ledger:checkJSSupport false
bundle.js:1 removeDeleted SyntaxError: Unexpected string in JSON at position 17
    at JSON.parse (<anonymous>)
    at bundle.js:1
    at Array.reduce (<anonymous>)
    at r (bundle.js:1)
    at <anonymous>
(anonymous) @ bundle.js:1
bundle.js:1 ServiceWorker error TypeError: Failed to register a ServiceWorker: An unknown error occurred when fetching the script.
(anonymous) @ bundle.js:1
bundle.js:1 ws::_onMessage 

-------------***************-------------> HERE IT SHOWS SEVERAL OF MY JSON KEY FILES.  I removed them for privacy.

 SyntaxError: Unexpected string in JSON at position 17
    at JSON.parse (<anonymous>)
    at bundle.js:1
    at Array.reduce (<anonymous>)
    at r (bundle.js:1)
    at bundle.js:1
    at t.value (bundle.js:1)
value @ bundle.js:1
bundle.js:1 ws::_onMessage 

-------------***************-------------> HERE IT SHOWS SEVERAL OF MY JSON KEY FILES.  I removed them for privacy.

 SyntaxError: Unexpected string in JSON at position 17
    at JSON.parse (<anonymous>)
    at bundle.js:1
    at Array.reduce (<anonymous>)
    at r (bundle.js:1)
    at bundle.js:1
    at t.value (bundle.js:1)
value @ bundle.js:1
bundle.js:1 loadAccounts SyntaxError: Unexpected string in JSON at position 17
    at JSON.parse (<anonymous>)
    at bundle.js:1
    at Array.reduce (<anonymous>)
    at r (bundle.js:1)
    at <anonymous>
(anonymous) @ bundle.js:1
bundle.js:1 [DAPP] %cElectron Security Warning
bundle.js:1 could not register ServiceWorker after 2.5s
(anonymous) @ bundle.js:1
bundle.js:1 [DAPP] This inject.js has been injected by the shell.
bundle.js:1 [DAPP] Requesting API communications token for v1
bundle.js:1 [DAPP] Deprecation: Dapps should only used the exposed EthereumProvider on `window.ethereum`, the use of `window.parity` and `window.web3` will be removed in future versions of this injector
bundle.js:1 [DAPP] Ledger:checkJSSupport
bundle.js:1 [DAPP] v1: starting Status Provider...
bundle.js:1 [DAPP] SW error
bundle.js:1 [DAPP] v1: starting Status Provider...
bundle.js:1 [DAPP] Received API communications token REMOVEDFORPRIVACY
bundle.js:1 [DAPP] v1: started Status Provider
bundle.js:1 [DAPP] v1: starting Personal Provider...
bundle.js:1 [DAPP] v1: started Status Provider
bundle.js:1 [DAPP] v1: starting Personal Provider...
bundle.js:1 [DAPP] registry at REMOVEDFORPRIVACY, code REMOVEDFORPRIVACY, version 2
2bundle.js:1 [DAPP] removeDeleted
5bundle.js:1 [DAPP] [lookupAddress]
2bundle.js:1 [DAPP] Uncaught SyntaxError: Unexpected string in JSON at position 17
bundle.js:1 [DAPP] could not register SW after 2.5s`

**Comment by axelchalon** [comment] 2018-06-04 12:09
I also don't think this is a scaling issue (tried reproducing the issue with 80 accounts and they all showed up fine in the UI).

I strongly suspect this is due to the fact that inside one (or several) of your JSON key files, the `meta` field isn't valid JSON. This was probably due to an issue we had where editing account information (name or metadata) on Parity UI used to sometimes corrupt the json file (fixed in https://github.com/parity-js/shell/issues/106). Invalid `meta` value doesn't throw a warning when launching Parity.

@amaurymartiny Most likely the location of the error (stacktraces match) is:
https://github.com/parity-js/api/blob/4b9e4c64f0ae568bfb372eba38f1830dd339b0a8/src/format/output.js#L36 If I edit one of my json key files and put an invalid `meta` value, there's a console error and no account shows up in Parity Wallet.

@lampshade9909 In the meantime you can locate the corrupt JSON file and edit its `meta` field to be valid JSON (or empty json for example: `"meta":"{}"`)

**Closed** 2018-06-04 12:37 UTC
Labels: F3-annoyance, M0 - wallet, P9-somedaymaybe
